sudo: required
language: node_js
notifications:
  email: adroaldoaragao@yahoo.com.br
node_js: 
  - 10.16.3
services:
  - postgresql
env:
  global:
  - NODE_ENV: test
  - TRAVIS: true
addons:
  postgresql: "11.5"
before_install:
  - sudo apt-get update
  - sudo apt-get install -y postgresql-11 postgresql-client-11
  - sudo cp /etc/postgresql/{9.6,11}/main/pg_hba.conf
  - sudo systemctl start postgresql
before_script:
  - psql --version
  - psql -c "create database ts_api_test;" -U postgres
  - npm i -g sequelize-cli gulp-cli
  - cd server/
  - npm install
  - gulp
script:
  - npm run dbconfig
  - npm run unit-test
  - npm run integration-test